### ISSUE TITLE
Suggestion: Remove mod icons from list

### ISSUE THREAD

**Issue by Aegarain** [Deli-Collective/DeliCounter#10]
We're getting to a point where there are too many mods for the manager to download every icon at once, so they slowly pop in, which makes ux feel B A D. Additionally, most of the icons are displayed too small to be recognizable, as many are just pictures of the added/modified object. Even Meatyceiver, which has an actual logo, is displayed too small to read the text. My proposal is that icons are removed from the list entirely, and are instead shown in the info panel, regardless of the mod.

**Comment by Slingexe** [comment]
You can make it an option in the settings menu.
Some people may like the icons

**Comment by nrgill28** [comment]
As of v1.0.0 a new option has been added to select how mods appear in the listings, including one which removes the icons.
