### ISSUE TITLE
Something went wrong and the application can't start (parameter path1 cannot be null)

### ISSUE THREAD

**Issue by vaqxai** [Deli-Collective/DeliCounter#13]
https://i.imgur.com/2ZX4Lk7.png

**Comment by nrgill28** [comment]
Hi, could you describe your error in more detail please? Is this your first time using Deli Counter? If not, what did you do before this error happened?
Additionally, please ensure that you are running the latest version of Deli Counter and that your game is installed via Steam

**Comment by nrgill28** [comment]
This issue should be fixed in [v1.1.1](https://github.com/Deli-Collective/DeliCounter/releases/tag/v1.1.1). Please update the app and let me know if the error persists.
