### ISSUE TITLE
DeliCounter.exe not opening

### ISSUE THREAD

**Issue by StronksLIVE** [Deli-Collective/DeliCounter#15]
Whenever I try to open it,  it doenst let me open it for some reason. No error messages or anything it just doesnt want to open. Have tryed older versions so I dont know what to do

**Comment by nrgill28** [comment]
This sounds like an issue with how you downloaded the program. Some troubleshooting steps I can think of:

* Make sure that you have [.NET 5 x64](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-5.0.6-windows-x64-installer) installed. It must be the x64 version, x86 will not work.
* Make sure you are extracting the program from the release zip and that after extraction all the files from the zip are still there
* Try placing the extracted application folder on your desktop, sometimes Windows permissions can be weird.

**Comment by OrangeBruh** [comment]
I have had the same problem, it wont open even though i tried the troubleshooting tips...

**Comment by nrgill28** [comment]
I've had some discussion with @OrangeBruh via Discord and this is not an issue that I believe is on my end. Unfortunately when _absolutely nothing_ happens it makes it very difficult to locate what is causing the problem and it could be anything. I will close this issue as it is not something I am able to find, let alone fix or provide a solution for.
