### ISSUE TITLE
Something went wrong and the application needs to exit. Value cannot be null. (Parameter "path") trying to clean install

### ISSUE THREAD

**Issue by Terminal-Rat** [Deli-Collective/DeliCounter#16]
When opening the program for the first time, I get the option to clean my game installation. If I say yes to that option, the program crashes with the above error. When I try to reopen the program after that, it gives an error that .Net is required and presents the option to download it. The only way to get the program to open is to extract a fresh copy. I believe the error has to do with the fact that I haven't set the path to my install, but there isn't an option to do that before it asks if I want to clean it, and I can't find anywhere to trigger the cleaning again after I set the path. 

Can you either 1: Require the path to the game be set when you first open the program, prior to asking if you want to clean the install, or 2: Add an option to clean the install in the settings menu somewhere so it can be triggered manually. (This might be a good thing to include anyways).

Thanks!

**Comment by nrgill28** [comment]
This sounds really strange. You're saying that after (successfully) opening the program once, any subsequent attempts present you with the ".NET is required" dialog?  I'm not quite sure if that's an issue on my end, maybe try reinstalling .NET

I can fix the other issue no problem though.

**Comment by Terminal-Rat** [comment]
Yeah. I did do an reinstall of .NET which fixed that portion as far as I can tell.

**Comment by nrgill28** [comment]
Okay cool. I have the other issue fixed already and it'll be included in the next release.
