### ISSUE TITLE
DeliCounter refuses to open

### ISSUE THREAD

**Issue by kaar-the-derg** [Deli-Collective/DeliCounter#18]
Whenever I try to open DeliCounter, it just doesn't seem to open. It seems to load but after 2 seconds or so, it stops and doesn't open. No error, nothing

**Comment by nrgill28** [comment]
Can you try both of these versions: [1.1.2](https://github.com/Deli-Collective/DeliCounter/releases/tag/v1.1.2) and [1.1.1](https://github.com/Deli-Collective/DeliCounter/releases/tag/v1.1.1). As per the release notes in 1.1.2, it is updated for the Steam beta and will not work if you are not in the Steam beta.

**Comment by kaar-the-derg** [comment]
1.1.2 works, 1.1.1 and 1.1.0 didn't open. All is fixed now, thanks!
