### ISSUE TITLE
unable to download mods for h3vr

### ISSUE THREAD

**Issue by kc9pop** [Deli-Collective/DeliCounter#19]
repository status says its up to date and gives the green checkmark on start but if i refresh it says offline. the repository in settings its correct " https://github.com/Deli-Collective/Deli-Counter-Database "

any time i try to download something it gives

error
an operation did not complete successfully: 
could not download the file: the request was aborted: the request was canceled

**Comment by nrgill28** [comment]
BoneTome (the website where many mods are hosted) has been having lots of issues recently and this is almost certainly related to that. I can confirm that you are not the only one having issues, so we'll just have to wait until the author of BoneTome sorts this out.

**Comment by kc9pop** [comment]
thank you for responding quick
