### ISSUE TITLE
an exception occurred during a webclient request 

### ISSUE THREAD

**Issue by KnightCoco** [Deli-Collective/DeliCounter#20]
Just installed Deli and I keep getting "an exception occurred during a webclient request" along with downloads freezing, I've got the storage space so I am lost.

**Comment by nrgill28** [comment]
It's very possible this issue is caused by BoneTome's (The host for most mods) current frequent downtime. Just try it again after a little while and it should work again. If that doesn't help unfortunately there isn't much I can do at the moment until the issues on BT's end are fixed
