### ISSUE TITLE
Show mod icons in info sidebar

### ISSUE THREAD

**Issue by Aegarain** [Deli-Collective/DeliCounter#5]
A lot of the custom object icons are just pictures of the added objects. The manager displays icons too small to be able to look at these icons. A possible solution is to have the mod icons appear in the sidebar that holds a selected mod's info

**Comment by nrgill28** [comment]
This is something I would like to look into too. I might add a new (optional) field in the database json files for such an image.

**Comment by nrgill28** [comment]
Mod preview images implemented in 0.1.11
